app = "energyopti-pro"
kill_signal = "SIGINT"
kill_timeout = 5
[env]
FLET_SESSION_TIMEOUT = "60"
[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
[[services]]
protocol = "tcp"
internal_port = 50052
[[services.ports]]
port = 50052
[[services.regions]]
region = "lax"
