services:
  - type: web
    name: energyopti-pro-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.energyopti_pro.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: energyopti-pro-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: energyopti-pro-redis
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CME_API_KEY
        sync: false
      - key: ICE_API_KEY
        sync: false
      - key: NYMEX_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: ALLOWED_ORIGINS
        value: https://energyopti-pro-frontend.vercel.app,https://energyopti-pro.vercel.app

databases:
  - name: energyopti-pro-postgres
    databaseName: energyopti_pro
    user: energyopti_user
    plan: free

services:
  - type: redis
    name: energyopti-pro-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
