@echo off 
echo Validating frontend dependencies... 
npm install 
echo Validating TypeScript build... 
npm run build 
echo Validating Vercel configuration... 
vercel deploy --prod --confirm 
echo Validating backend tests... 
cd ../backend 
set PYTHONPATH=%D:\Documents\QuantaEnergi\frontend%\..;%D:\Documents\QuantaEnergi\backend\..;D:\Documents\QuantaEnergi\backend\..;D:\Documents\QuantaEnergi\backend\..;D:\Documents\QuantaEnergi\frontend\..;D:\Documents\QuantaEnergi\backend\..;D:\Documents\QuantaEnergi\backend\..;D:\Documents\QuantaEnergi\backend\..;D:\Documents\QuantaEnergi\backend\..;D:\Documents\QuantaEnergi\backend\..;D:\Documents\QuantaEnergi\backend\..;D:\Documents\QuantaEnergi\backend\..;D:\Documents\QuantaEnergi\backend;D:\Documents\QuantaEnergi\backend;%PYTHONPATH%% 
pytest tests/validation_tests.py 
echo Validation complete! 
