# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: energy.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65nergy.proto\"\x1f\n\rEnergyRequest\x12\x0e\n\x06source\x18\x01 \x01(\t\"\x1f\n\x0e\x45nergyResponse\x12\r\n\x05price\x18\x01 \x01(\x02\x32\x46\n\rEnergyService\x12\x35\n\x10StreamEnergyData\x12\x0e.EnergyRequest\x1a\x0f.EnergyResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'energy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENERGYREQUEST']._serialized_start=16
  _globals['_ENERGYREQUEST']._serialized_end=47
  _globals['_ENERGYRESPONSE']._serialized_start=49
  _globals['_ENERGYRESPONSE']._serialized_end=80
  _globals['_ENERGYSERVICE']._serialized_start=82
  _globals['_ENERGYSERVICE']._serialized_end=152
# @@protoc_insertion_point(module_scope)
