name: energyopti_pro_mobile
description: Next-Generation Energy Trading Platform Mobile App
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP & WebSocket
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Charts & Visualization
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^23.1.44
  
  # Forms & Validation
  form_builder_validators: ^9.1.0
  flutter_form_builder: ^9.1.1
  
  # Authentication & Security
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  firebase_messaging: ^14.7.10
  
  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  
  # Utils
  uuid: ^4.2.1
  crypto: ^3.0.3
  logger: ^2.0.2+1
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  
  # Firebase (optional)
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  
  # Biometric Authentication
  local_auth_android: ^1.0.35
  local_auth_ios: ^1.1.5
  
  # Platform Specific
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.5
  
  # Coverage
  coverage: ^1.6.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: assets/translations
  output_dir: lib/generated
