/**
 * Auto-generated TypeScript types from backend OpenAPI schema
 * This file is automatically generated - do not edit manually
 * Run: npm run generate-types to regenerate
 */

// This file will be populated by the openapi-typescript-codegen tool
// when we set up the automated type generation pipeline

export interface GeneratedTypes {
  // Placeholder for generated types
  // Will be replaced by actual generated types from backend
}
