global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: quantaenergi
    environment: production

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # QuantaEnergi Backend
  - job_name: 'quantaenergi-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true

  # QuantaEnergi Frontend
  - job_name: 'quantaenergi-frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis Cluster Nodes
  - job_name: 'redis-cluster'
    static_configs:
      - targets:
        - 'redis-node-1:6379'
        - 'redis-node-2:6379'
        - 'redis-node-3:6379'
        - 'redis-node-4:6379'
        - 'redis-node-5:6379'
        - 'redis-node-6:6379'
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s

  # Nginx Load Balancer
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 15s
    scrape_timeout: 5s

  # Node Exporter (if running on host)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Docker Daemon
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Custom QuantaEnergi Metrics
  - job_name: 'quantaenergi-custom'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/custom-metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
